### ISSUE TITLE
jitsi not working

### ISSUE THREAD

**Issue by al2suarez** [lfache/awesome-traefik#1]
Hi there,

Did a fresh install of awesome-traefik and successfully ran traefik on vps, then followed the instructions for jitsi... the jitsi website comes up successfully, but when you start a video chat I immediately get "You have been disconnected".  When I run docker-compose up, i don't see any errors... the logs look normal with no errors shown.  Obviously I setup the host name correctly since it comes up... I successfully generated the passwords... I set the .env as follows:

CONFIG=./jitsi-meet-cfg

# Exposed HTTP port
HTTP_PORT=80

# Exposed HTTPS port
HTTPS_PORT=443

# System time zone
TZ=America/Chicago

# Public URL for the web service
PUBLIC_URL=https://jitsi.testing.me

# IP address of the Docker host
# See the "Running behind NAT or on a LAN environment" section in the README
DOCKER_HOST_ADDRESS=1.2.3.4

Not sure what else to do here.. I googled "You have been disconnected" but got lots of stuff.   Am I missing something?  Any hint would be appreciated, Thank you.

**Comment by ottobaer** [comment]
I think this is a Jitsi bug. I opened a bugreport in december for that.

**Comment by Broz3r** [comment]
Hi ! I faced the exact same issue and I figure out that the video bridge port is not available outside the docker. You need to add some traefik configuration to expose the :1000 upd port.

Under the `jvb` service add the following lines:
```
labels:
    traefik.udp.routers.jvb.entrypoints: video
    traefik.udp.routers.jvb.service: jvb
    traefik.udp.services.jvb.loadbalancer.server.port: 10000
```
